import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { getLDrawColor } from "../src/generation/colorCatalog.js";
import { SUPPORTED_PARTS } from "../src/generation/partCatalog.js";

const PART_IDS = Object.freeze({
  "brick:1x1": "3005",
  "brick:1x2": "3004",
  "brick:1x3": "3622",
  "brick:1x4": "3010",
  "brick:1x6": "3009",
  "brick:1x8": "3008",
  "brick:1x12": "6112",
  "brick:2x2": "3003",
  "brick:2x3": "3002",
  "brick:2x4": "3001",
  "brick:2x6": "2456",
  "brick:2x8": "3007",
  "plate:1x2": "3023",
  "plate:1x3": "3623",
  "plate:1x4": "3710",
  "plate:1x6": "3666",
  "plate:1x8": "3460",
  "plate:1x10": "4477",
  "plate:2x2": "3022",
  "plate:2x3": "3021",
  "plate:2x4": "3020",
  "plate:2x6": "3795",
  "plate:2x8": "3034",
  "plate:2x10": "3832",
  "plate:2x16": "4282",
  "plate:4x4": "3031",
  "plate:4x6": "3032",
  "plate:4x10": "3030",
  "plate:4x12": "3029",
  "plate:6x6": "3958",
  "plate:6x8": "3036",
  "plate:6x10": "3033",
});

function parseCsvLine(line) {
  const cells = [];
  let value = "";
  let quoted = false;

  for (let index = 0; index < line.length; index += 1) {
    const character = line[index];

    if (character === '"') {
      if (quoted && line[index + 1] === '"') {
        value += '"';
        index += 1;
      } else {
        quoted = !quoted;
      }
    } else if (character === "," && !quoted) {
      cells.push(value);
      value = "";
    } else {
      value += character;
    }
  }

  cells.push(value);
  return cells;
}

function canonicalPartKey(label) {
  const match = String(label).trim().toLowerCase().match(/^(brick|plate)\s+(\d+)\s*x\s*(\d+)$/);

  if (!match) {
    throw new Error(`Unknown inventory piece label: ${label}`);
  }

  return `${match[1]}:${match[2]}x${match[3]}`;
}

export function normalizeFixedInventoryCsv(csvText) {
  const lines = csvText.replace(/^\uFEFF/, "").trim().split(/\r?\n/);
  const headers = parseCsvLine(lines.shift());

  if (headers.join(",") !== "piece_type,color,quantity") {
    throw new Error(`Unexpected inventory CSV headers: ${headers.join(",")}`);
  }

  return lines.map((line, index) => {
    const [pieceType, colorName, quantityText] = parseCsvLine(line);
    const partKey = canonicalPartKey(pieceType);
    const partId = PART_IDS[partKey];
    const part = SUPPORTED_PARTS[partId];
    const color = getLDrawColor(colorName);
    const count = Number(quantityText);

    if (!partId || !part) {
      throw new Error(`Unknown inventory part at CSV row ${index + 2}: ${pieceType}`);
    }

    if (!color) {
      throw new Error(`Unknown inventory color at CSV row ${index + 2}: ${colorName}`);
    }

    if (!Number.isInteger(count) || count <= 0) {
      throw new Error(`Invalid inventory quantity at CSV row ${index + 2}: ${quantityText}`);
    }

    return {
      label: part.label,
      category: part.category,
      part_id: part.part_id,
      ldraw_id: part.ldraw_id,
      rebrickable_part_num: part.part_id,
      color_name: color.color_name,
      color_id: color.color_id,
      count,
      supported: true,
    };
  });
}

export function inventoryModuleSource(items) {
  return `/** Generated by scripts/buildFixedDemoInventory.js from the committed CSV. */\n` +
    `export const fixedDemoInventory = ${JSON.stringify({
      inventory_id: "fixed-demo-inventory-20260719",
      source: "manual_test_fixture",
      items,
    }, null, 2)};\n`;
}

async function main() {
  const csvUrl = new URL(
    "../demo-assets/lego-inventory-for-model-generation-20260719.csv",
    import.meta.url,
  );
  const outputUrl = new URL(
    "../src/generation/fixtures/fixedDemoInventory.js",
    import.meta.url,
  );
  const csvText = await readFile(csvUrl, "utf8");
  const items = normalizeFixedInventoryCsv(csvText);
  await writeFile(outputUrl, inventoryModuleSource(items));
}

if (fileURLToPath(import.meta.url) === process.argv[1]) {
  await main();
}
