/** @type {import("../types.js").Inventory} */
export const daisyInventory = {
  inventory_id: "daisy-demo",
  source: "manual_test_fixture",
  items: [
    {
      label: "2x4 brick",
      category: "brick",
      part_id: "3001",
      ldraw_id: "3001.dat",
      rebrickable_part_num: "3001",
      color_name: "green",
      color_id: "2",
      count: 16,
      supported: true,
    },
    {
      label: "2x2 brick",
      category: "brick",
      part_id: "3003",
      ldraw_id: "3003.dat",
      rebrickable_part_num: "3003",
      color_name: "green",
      color_id: "2",
      count: 4,
      supported: true,
    },
    {
      label: "1x2 brick",
      category: "brick",
      part_id: "3004",
      ldraw_id: "3004.dat",
      rebrickable_part_num: "3004",
      color_name: "green",
      color_id: "2",
      count: 8,
      supported: true,
    },
    {
      label: "2x4 brick",
      category: "brick",
      part_id: "3001",
      ldraw_id: "3001.dat",
      rebrickable_part_num: "3001",
      color_name: "white",
      color_id: "15",
      count: 6,
      supported: true,
    },
    {
      label: "2x2 brick",
      category: "brick",
      part_id: "3003",
      ldraw_id: "3003.dat",
      rebrickable_part_num: "3003",
      color_name: "white",
      color_id: "15",
      count: 8,
      supported: true,
    },
    {
      label: "1x2 brick",
      category: "brick",
      part_id: "3004",
      ldraw_id: "3004.dat",
      rebrickable_part_num: "3004",
      color_name: "white",
      color_id: "15",
      count: 6,
      supported: true,
    },
    {
      label: "2x2 brick",
      category: "brick",
      part_id: "3003",
      ldraw_id: "3003.dat",
      rebrickable_part_num: "3003",
      color_name: "yellow",
      color_id: "14",
      count: 4,
      supported: true,
    },
  ],
};
