/** @type {import("../types.js").Inventory} */
export const houseFlyInventory = {
  inventory_id: "house-fly-demo",
  source: "manual_test_fixture",
  items: [
    {
      label: "2x4 brick",
      category: "brick",
      part_id: "3001",
      ldraw_id: "3001.dat",
      rebrickable_part_num: "3001",
      color_name: "dark bluish gray",
      color_id: "72",
      count: 4,
      supported: true,
    },
    {
      label: "2x4 brick",
      category: "brick",
      part_id: "3001",
      ldraw_id: "3001.dat",
      rebrickable_part_num: "3001",
      color_name: "black",
      color_id: "0",
      count: 2,
      supported: true,
    },
    {
      label: "2x2 brick",
      category: "brick",
      part_id: "3003",
      ldraw_id: "3003.dat",
      rebrickable_part_num: "3003",
      color_name: "black",
      color_id: "0",
      count: 7,
      supported: true,
    },
    {
      label: "2x2 brick",
      category: "brick",
      part_id: "3003",
      ldraw_id: "3003.dat",
      rebrickable_part_num: "3003",
      color_name: "dark bluish gray",
      color_id: "72",
      count: 6,
      supported: true,
    },
    {
      label: "1x2 brick",
      category: "brick",
      part_id: "3004",
      ldraw_id: "3004.dat",
      rebrickable_part_num: "3004",
      color_name: "black",
      color_id: "0",
      count: 16,
      supported: true,
    },
    {
      label: "1x2 brick",
      category: "brick",
      part_id: "3004",
      ldraw_id: "3004.dat",
      rebrickable_part_num: "3004",
      color_name: "red",
      color_id: "4",
      count: 2,
      supported: true,
    },
    {
      label: "1x1 brick",
      category: "brick",
      part_id: "3005",
      ldraw_id: "3005.dat",
      rebrickable_part_num: "3005",
      color_name: "black",
      color_id: "0",
      count: 10,
      supported: true,
    },
    {
      label: "2x4 plate",
      category: "plate",
      part_id: "3020",
      ldraw_id: "3020.dat",
      rebrickable_part_num: "3020",
      color_name: "translucent light blue",
      color_id: "43",
      count: 6,
      supported: true,
    },
    {
      label: "2x2 plate",
      category: "plate",
      part_id: "3022",
      ldraw_id: "3022.dat",
      rebrickable_part_num: "3022",
      color_name: "translucent light blue",
      color_id: "43",
      count: 2,
      supported: true,
    },
  ],
};
