/** @type {import("../types.js").Inventory} */
export const sandcastleInventory = {
  inventory_id: "sandcastle-demo",
  source: "manual_test_fixture",
  items: [
    {
      label: "2x4 brick",
      category: "brick",
      part_id: "3001",
      ldraw_id: "3001.dat",
      rebrickable_part_num: "3001",
      color_name: "tan",
      color_id: "19",
      count: 16,
      supported: true,
    },
    {
      label: "2x2 brick",
      category: "brick",
      part_id: "3003",
      ldraw_id: "3003.dat",
      rebrickable_part_num: "3003",
      color_name: "tan",
      color_id: "19",
      count: 20,
      supported: true,
    },
    {
      label: "1x2 brick",
      category: "brick",
      part_id: "3004",
      ldraw_id: "3004.dat",
      rebrickable_part_num: "3004",
      color_name: "tan",
      color_id: "19",
      count: 10,
      supported: true,
    },
    {
      label: "1x1 brick",
      category: "brick",
      part_id: "3005",
      ldraw_id: "3005.dat",
      rebrickable_part_num: "3005",
      color_name: "tan",
      color_id: "19",
      count: 8,
      supported: true,
    },
  ],
};
